### ISSUE TITLE
submit handler bypasses required

### ISSUE THREAD

**Issue by millette** [pablo-abc/felte#106]
If I declare form inputs with `required`, or type `email`, those conditions are bypassed and the form is always submitted. Can validation leverage the html form declaration?

**Comment by millette** [comment]
Gotcha https://felte.dev/docs/solid/reporters#using-the-constraint-validation-api

**Comment by pablo-abc** [comment]
> Gotcha https://felte.dev/docs/solid/reporters#using-the-constraint-validation-api

This refers to _displaying_ errors from any other validator using the CVAPI, not using the browser's validation. If it's about using the CVAPI to _validate_ your values, there was #48 , but I had no time to get back into it and it's been a bit abandoned right now. I'm interested on going back to it, though.

When using Felte, `novalidate` is added to your `<form>` element. This is due to two things:

1. If you're using Felte anyway, it was figured this is the way you'd want to handle validation and reporting. Using the browser's API removes a lot of what Felte gives you.
2. This is the main reason: The browser handles validation of these fields _before_ submit, so Felte has no way to get to these messages. If `novalidate` were to be removed, these validation errors would be displayed using the browser's tooltips rather than Felte. That's what #48 is about.

If you want Felte to obtain the messages from the browser's validation, I could find some time to revive #48. If there's a reason where you'd think appropriate to let the browser do validation (despite the second reason I described above), adding a configuration option to Felte would be trivial. Either way, if either of the previous applies to you, reopening this seems appropriate.

**Comment by millette** [comment]
Yeah, I've had time now to read thru other issues (great to read you and @benbender exchange on the topic). I don't want to add to the noise.

I might try to "add novalidate"/"remove novalidate" and see what it gets us, but I'm rather swamped with work right now.
