### ISSUE TITLE
initialValues is not working

### ISSUE THREAD

**Issue by abhijit-kar** [pablo-abc/felte#12]
I noticed one issue, the initial Values is not working as expected.

![Screenshot from 2021-03-31 14-15-04](https://user-images.githubusercontent.com/25662120/113116912-8d7d9a00-922b-11eb-8e0e-ab4b8a050a9f.png)

## Praise
Thanks for making such a wonderful library. (I don't have to combine svelte-forms-lib with svelte-tippyjs and svelte-scroll, just to achieve what you have done!).
Felte solves all the problems I wanted a form library to solve. For example svelte-forms-lib:
1. Doesn't auto focus on error field.
2. Has old school way of error message support, unlike using Tippy.js.
3. Too verbose, as I have to include onChange on every field and values as well.

## P.S.
I am going to write a blog post about this library, at the end of this week, on my blog [Derpy Coder](https://www.derpycoder.com)
And I am using this library in my project [Quiller Bee](https://www.quillerbee.com), repo [Quiller Bee - Dgraph Branch](https://github.com/quillerbee/quillerbee/tree/dgraph)

**Comment by pablo-abc** [comment]
Hey! Thank you so much for giving Felte an opportunity!

I think I don't understand what is the issue you're showing me here 😅. Are you setting initial values for those fields and they're not appearing as expected? If so, the intended use case for inputs "controlled" by Felte (e.g. not using `bind:value`) is for you to set it using said input's `value` attribute. I mentioned this in [the docs](https://felte.dev/docs#default-data).

The reason is that, as long as you're letting Felte do all the work, building your form should feel almost completely like building a normal HTML5 form. Re reading the docs I do feel the docs were not that clear on that part so I'll update them.

If that was not the issue I'll need some more clarification 😅.

**Comment by pablo-abc** [comment]
Btw, a breaking change is coming to `@felte/reporter-tippy` for it to have a more consistent API with the other packages, and to allow to pass options to `Tippy` itself. Just a heads up 😄. As soon as I publish @felte/reporter-tippy@0.2.0 you will need to use it like so: `extend: tippyReporter()` in order to have the same behaviour as before.

Docs will be updated accordingly.

**Comment by abhijit-kar** [comment]
@pablo-abc,

Thanks for the heads up about `@felte/reporter-tippy`. I'll update it as soon as you release.

I'm so glad that you have decided to not mess with the default HTML form behaviors. I have been through the [default data docs](https://felte.dev/docs#default-data), and I understand that Felte is able to pick up values from the input fields itself.

I have 2 questions:
1. Does Felte pickup values from form after initialization? (Like after results of an API call comes in?)
1. Or is it possible to initialize the form in bulk? (and not individual fields like: `setField('account.email', 'default@email.dev', false);`)

Say a user edits an already existing content, I want to be able to fill the whole form with data from API.

That's how I was using initialValues in Svelte Forms Lib.

i.e. 

```javascript
initialValues: {
    title: "",
    url: "",
    salary: {
        min: "",
        max: "",
        currency: "USD",
    },
},
```

Based on your answer, I might have to change my approach a little.
i.e. Either loading the Form UI, after the API returns data or the data will appear after the form UI is visible.

**Comment by abhijit-kar** [comment]
Hey @pablo-abc,

After using `bind:value`, the default values are working.

**Comment by pablo-abc** [comment]
`initialValues` is only used after during initialisation. But your use case is quite valid and something I hadn't tested yet. I do believe this is something that could be done via a new helper function 🤔. I would just need to export a function that I'm using internally anyway, so I'll publish a patch with this to cover your use case.

**Comment by pablo-abc** [comment]
I've added this to felte@0.6.1, I've [updated the docs](https://felte.dev/docs#setfields) as well.

Feel free to close this if this solves your issue!

**Comment by abhijit-kar** [comment]
Thank you for promptly adding a functionality.
