### ISSUE TITLE
Setting input value in the DOM does not update the form state for SolidJS

### ISSUE THREAD

**Issue by thdxr** [pablo-abc/felte#120]
I'm not sure if this is actually supposed to work because I'm unfamiliar with how Felte works under the hood but if you take the following
```
export function Sample() {
  const [test, setTest] = createSignal(0)

  const form = createForm<{
    test: string
  }>({
    initialValues: {},
    onSubmit: (values) => {
      console.log(values)
    }
  })

  setInterval(() => {
    setTest(Math.random())
  }, 1000)

  createEffect(() => {
    console.log(form.data(d => d.test))
  })

  return <form ref={form.form}><input type="hidden" value={test()} /></form>
}
```

The form state never updates.  Using `setField` does work but in my use case the input is in a nested component and I'm trying to avoid passing `form` all the way down

**Comment by pablo-abc** [comment]
So, yeah. Pre 1.0 we did listen to changes directly to `value` by proxying that specific property. This lead to a lot of issues due to race conditions that made it hard to maintain. Felte relies on events to keep state of your form and setting the `.value` prop does not dispatch any event, so starting on 1.0.0 the recommendation is one of these:

1. Use helper's directly (e.g. `setField`). Which might not work for you since your component.
2. Use [`createField`](https://felte.dev/docs/solid/custom-form-controls#using-createfield). This would allow you to make a control that can be nested without needing to pass any helpers as props.

**Comment by thdxr** [comment]
ah I see totally missed `createField` - that fixes my problem nicely.  But is there no way to build a component that's ignorant of felte entirely but still works with it? Is there some event I can trigger whenever the value changes?

**Comment by pablo-abc** [comment]
You can dispatch an `input` event or `change` event from the element itself, but this requires having a reference to the native element. E.g. 

```jsx
export function Sample() {
  const [test, setTest] = createSignal(0)

  const form = createForm<{
    test: string
  }>({
    initialValues: {},
    onSubmit: (values) => {
      console.log(values)
    }
  })

  setInterval(() => {
    setTest(Math.random())
  }, 1000)

  createEffect(() => {
    console.log(form.data(d => d.test))
  })

  let inputEl;
  
  createEffect(() => {
    inputEl.value = test();
    inputEl.dispatchEvent(new Event('change', { bubbles: true }));
  });

  return <form ref={form.form}><input ref={inputEl} type="hidden" /></form>
}
```

Note that we treat `change` and `input` events differently. `change` set the field to `touched`. For `input` events you'd need to combine it with a `focusout` event. And make sure they bubble!

But this is what `createField` does under the hood (it also adds an `<input type="hidden">` if you didn't add your own). It doesn't really rely on anything Felte specific.

**Comment by pablo-abc** [comment]
I'm closing this since it's not an issue! But feel free to ask further questions if you need more assistance
