### ISSUE TITLE
The latest value is not obtained after the input has been modified by code manipulation

### ISSUE THREAD

**Issue by EndureBlaze** [pablo-abc/felte#187]
### Describe the bug

I want to modify the value of the input through code, for example if I get the return value from another special component and want to return it uniformly from the form.

For example, in the following example, the target value I want to get is `{test: 'test value', test2: 'test2 value'}`, but I actually get `{test: '', test2: ''}`

### Which package/s are you using?

@felte/solid (SolidJS)

### Environment

- OS: macOS 12
- Browser: Chrome, Firefox
- Version: @felte/solid: ^1.2.6

### Small reproduction example

https://stackblitz.com/edit/solidjs-templates-4l27ym?file=src%2FApp.tsx

**Comment by pablo-abc** [comment]
I'd advise here using Felte as the "source of truth" for your input's value and not updating it programatically. Felte relies on events dispatched by the inputs/form in order to keep track of its state. Programatically changing the value of an input does not trigger any event so there's no way for Felte to know this.

In your example I'd avoid using a separate signal, getting the value of the input from the `data` store and using the [`setFields`](https://felte.dev/docs/solid/helper-functions#setters) helper to update the value of the input programatically. That way you'd update both the value on the input _and_ the value Felte has stored simultaneously.

**Comment by EndureBlaze** [comment]
Thank you, I've used `setFields` to do what I wanted
