### ISSUE TITLE
`onSubmitError` not being called in extenders

### ISSUE THREAD

**Issue by goknsh** [pablo-abc/felte#192]
### Describe the bug

From the docs, when extending Felte, I understood that `onSubmitError` will be called when there is an error in the `onSubmit` function. However, this is not the case.

### Which package/s are you using?

felte (Svelte), @felte/common

### Environment

- OS: Windows 11
- Browser: Firefox
- Version: felte@1.2.6, @felte/common@1.1.3

### To reproduce

See reproduction example

### Small reproduction example

https://stackblitz.com/edit/vitejs-vite-nprkij?file=src/App.svelte

**Comment by pablo-abc** [comment]
This sounds like a documentation mistake on my part (extending Felte is something I did not expect that many people to try).

onSubmitError _needs_ there to be errors on the `errors` store for it to be called. For this reason it only gets called in two situations:

1. Errors triggered from client-side validation (`validate` function or validator extenders).
2. Errors from the server that are _also_ handled by the user on the `onError` call (since handling server errors on an extender might break users' expectations).

**Comment by goknsh** [comment]
Got it, thanks.
