### ISSUE TITLE
solid form values empty onSubmit

### ISSUE THREAD

**Issue by sysmat** [pablo-abc/felte#195]
### Describe the bug

- input value is set but when submit onSubmit value is empty

### Which package/s are you using?

@felte/solid (SolidJS)

### Environment

- OS: Win 10
- Browser: Chrome
- Version: "@felte/solid": "^1.2.6",
-   "solid-js": "^1.6.2",

### To reproduce

1. https://stackblitz.com/edit/solidjs-templates-brsbde?file=src/App.tsx
2. Click button edit
3. Click button Confirm
4. You will see empty values(also in browser console)

### Small reproduction example

https://stackblitz.com/edit/solidjs-templates-brsbde?file=src/App.tsx

**Comment by pablo-abc** [comment]
Hey! This seems to work for me if I change your call to `createForm` to this:

```typescript
  const { form } = createForm<Human>({
    initialValues: {
      name: prop?.human?.name,
      surname: prop?.human?.surname,
    },
    onSubmit: (human: Human) => {
      console.log('form.human=', human);
      prop.setHuman(human);
      console.log('solid.human=', prop.human);
      prop.edit(false);
    },
  });
```

`setInitialValues` lets you change your "initial values" _after_ the form has loaded.

I do need to check why Felte is not grabbing the values from your `value` props as initial values, though. That's the expected behaviour.
