### ISSUE TITLE
Support for validating fields with blur()

### ISSUE THREAD

**Issue by ileonardo-c** [pablo-abc/felte#20]
Is it possible to add an option in `DomReporterOptions` to choose the validation of the fields being `focus` or `blur`?

**Comment by pablo-abc** [comment]
If I'm understanding correctly, Felte already does that. Felte will display your errors as long as the field is `touched`.

The [examples on felte.dev](https://felte.dev) showcase this I feel.

If this is not the issue, I'd need some more context.

**Comment by ileonardo-c** [comment]
When you are typing the fields, they are being validated (focus), a good example is the use of e-mail, as it will only validate as soon as it finds the `@` and then the `.com`.

The idea is not to show the "error" during writing, but after the user leaves the field (blur)

**Comment by hmaesta** [comment]
Showing validation errors **while user is typing** is not a great UX. 

---

> all validation should be inline: that is, as soon as the user has **finished filling** in a field, an indicator should appear nearby if the field contains an error. 

_[Nielsen Norman Group](https://www.nngroup.com/articles/errors-forms-design-guidelines/)_

---

> **avoid validating on each keystroke** because in most cases you simply cannot validate until someone has finished typing their answer.

_[UX Planet](https://uxplanet.org/designing-more-efficient-forms-assistance-and-validation-f26a5241199d)_

---

Currently Felte start validating data as soon as user types the first letter:

![ScreenFlow](https://user-images.githubusercontent.com/741969/115037870-5357fd80-9ea5-11eb-8f8c-8890b29fad7f.gif)

**Comment by pablo-abc** [comment]
Ahh, I understand. I've labeled this as a bug, changing this will be trivial. This seems to be the desired default behaviour in text/password/email inputs in this case. Maybe leaving an option open for other triggers might be good as well?

Thanks a lot for the suggestion, btw!

**Comment by pablo-abc** [comment]
Confirming this should now be the default behaviour in felte@0.6.8

**Comment by pablo-abc** [comment]
So the current behaviour is:

- The user focuses and starts typing an invalid value, no errors for that field in the `errors` store.
- The user focuses out of the input, the `errors` store will now contain the validation message for that field.

Now this next part is where I've not found a good answer for, regarding when the user goes back to fix the error.

- Should validations again only happen on `blur`? If so, the user might have already typed a valid value but the error message will still be shown which I find might be a bit confusing.
- Should validations be done on every keystroke in this case? This would only happen _after_ the field is touched, so the initial validation would still only happen on blur. But it would mean that if the user goes back to fix the field, they would receive immediate feedback on when the value is valid. **_This is the current behaviour right now_**
- Is debouncing the validation an option? This seems like a good middle point while still allowing for keystroke validation after an error is already shown. But this would need to be configurable for some use-cases. And I do feel debouncing is something that should be left to the developer rather than built-in.

Feel free to test the current implementation and I'm certainly open to suggestion in order to improve UX and DX.

**Comment by hmaesta** [comment]
You chose the best option. If the input is _already_ invalid, it doesn't matter to keep showing that is invalid while user types – but it makes a lot of difference when the input is **validated** as soon as it gets an acceptable value.

We are already using with blur validation and it's working as expected so far. 

Thank you for your availability, Pablo.

**Comment by pablo-abc** [comment]
Thanks for answering! I'll close this now. Thanks a lot to you for giving Felte an opportunity!
