### ISSUE TITLE
Be able to setup a field level validation schema

### ISSUE THREAD

**Issue by outerlook** [pablo-abc/felte#25]
## Description
Hi! It would be nice to set some field level validation.

## Example
My example is a multi-step form that shares the same <form/> element. This form asks for phone, name and email.

<details>
<summary>HTML</summary>

```html
 STEP 1
<form>
	<input name='name'>
	<button type='submit'/>
</form>

 STEP 2
<form>
	<input name='phone'>
	<button type='submit'/>
</form>

STEP 3
<form>
	<input name='email'>
	<button type='submit'/>
</form>
```

</details>

I use zod for validating things.

And I'm using the following schema:

<details>
<summary>### Schema</summary>

```typescript
const validationSchema = z.object({
	name: z.string().nonempty(),
	phone: phoneRegexValidation,
	email: emailValidation
})

```

</details>

## Example's issue

Every step is required. But I can't use like that. If all of them are required for submitting, I can't use the button as a `submit` button for controlling my form. And I do have some clear options:

- Handle only the last button as submittable, control my "steps" out of `onSubmit` (a bit boilerplatey)
- Separate into 3 forms, one with each validation (less svelte composable components power)

There is an option I used on react, using the library [react-hook-form](https://github.com/react-hook-form/react-hook-form)

- dynamically setup my validationSchema when "step" changed
<details>

<summary>### Schema</summary>

```typescript
const validationSchema = step => z.object({
	name: z.string().nonempty(),
	phone: step > 0 ? phoneRegexValidation : optional,
	email: ztep > 1 ? emailValidation : optional
})
```

</details>

<details>
<summary>### Creating form context</summary>

```typescript
const { form } = createFormContext({
		validateSchema: validationSchema(step),
		onSubmit: values => {
			if (!isLastStep) step++;
			else submitToServer(values)
		}
	})
```

</details>

But it doesn't seems to work (it could be another issue if I did it right, but that's not the main request here)

## Svelte-action

I've being trying to create an svelte action to solve that:

<details>
<summary>### Implementation</summary>

```typescript
export const validate = (
	node: HTMLInputElement,
	{ schema }: { schema: z.Schema<any> }
) => {
	const listener = (ev: Event) => {
		try {
			schema.parse(node.value)
		} catch (e) {
			ev.preventDefault();
			ev.stopPropagation();
			ev.stopImmediatePropagation();
			const error = e as z.ZodError<any>
			node.setCustomValidity(error.message)
		}
	}
	node.form?.addEventListener('submit', listener)

	return {
		destroy: () => {
			node.form?.removeEventListener('submit', listener)
		}
	}
}
```

</details>

<details>
<summary>### Usage</summary>

```html
	<input
		use:validate={nameValidation}
		name="name"
	/>
```

</details>

But I'm having no success on that. It isn't preventing form `onSubmit` from being executed. I don't know how to achieve that outside felte.

## Further comments

The library I mentioned (react-hook-form) uses a different and less html native for subscribing new fields that can validate at this level.

[RHF validation docs](https://react-hook-form.com/get-started#Applyvalidation)

I mention them only for bringing examples of libraries that have this kind of field-level API (and are choosing to continue supporting it).

Another benefit of solving it would be composability problem. A form would not need to know every field that are inside them for validating purposes.

**Comment by pablo-abc** [comment]
Hi! Sorry for the long wait. I broke my arm and am just recovering.

So let's start with my thoughts on this:

1. I am sort of building this on a direction that would allow you to build your forms in a way that they would work both with or without JS. Taking this into account, the best approach is to have a "submit" button on each step, and each step being a different form. (With JS enabled each one being a different call to felts `createForm`). What does sound interesting in this sense is maybe creating another export from felte to create multiple forms each one with their own configuration. I'd have to think of a possible API for this (although I do think this might be a bit of overkill).

2. For using a separate "Next" button that Felte handles without submitting the form (this would work with JS only), I do see the issue you're presenting since you'd want to prevent a user from going to the next step without first validating the current one. For this the validator-zod packages (as well as the others) do export the function that validates the schema directly:

https://github.com/pablo-abc/felte/blob/f5bf1c6117481b1f042081892194780da5f200c2/packages/validator-zod/src/index.ts#L14-L32

So instead of "extending" felte with the validator you may use that function directly inside of your `validate` function. That way you may use a different schema whenever the step changes.

Do you feel one of these suggestions work for you? Or is there a specific API you might have in mind? I am completely open to suggestions

**Comment by outerlook** [comment]
Move fast and break things shouldn't be taken so seriously. Sorry for your arm.

It's interesting to know this "with or without JS" intention. With that in mind I do prefer to create an solution based on my app over that second suggestion's function and not grow the library API on a wrong direction. 

I will try that by tomorrow and I'll post it here how it ended being if this helps someone. Thanks!

**Comment by ryanrussell** [comment]
@outerlook @pablo-abc 

Currently trying to solve the same issue. 

Would be very helpful if you could share a multi-step form demo on a codesandbox if you find a solution you are happy with and feel like adheres to best practices.

Thanks!

**Comment by outerlook** [comment]
Here is at REPL

https://svelte.dev/repl/d83a688976fd466ab0a1d55400ab94f6?version=3.38.2

A bit simple but makes it, right?
There is this thing of already errored password input, but I kept it simple...

**Comment by outerlook** [comment]
So, the problem of a multi-step validation could be taken easily. But the other part of this issue is about a method of transfering validations to a input directly, something like HTML does with
```html
<input required min=6 name='phone'/>
```
but not possible if we want more complex validations.

```svelte
<input use:validate={...}/>
```

This api would be against the library direction as it requires some changes that could be only used with js?

Just asking, we can close the issue if is not the intention

**Comment by pablo-abc** [comment]
Hey all, after seeing #29 it seems that the most dev friendly way to solve for multi-step forms is to use a separate form per step. For a couple reasons:

1. As @ryanrussell mentioned on #29 if a single form is used and you use an `<input type="submit">` to go to the next step, the next step will show all validation errors since the form has already "submitted" and all fields have been "touched". This could be mitigated by setting the fields of the other steps to untouched. But it requires manual work and I don't see how Felte could do this internally since we would need to differentiate between an actual multi-step form from a simply a hidden field.

2. If using a `<button type="button">` to go to the next step then validation would need to be triggered manually using a helper. And again this would validate all fields of the form. As mentioned above, switching the validation schema per step might be an option but it's a little bit cumbersome.

If we do go towards the a separate form for each step route, would a helper to create multiple forms be useful at all? That seems to me like something trivial anyone could do if they actually need it on the project. Or having each step being a component with its own `createForm` call. I don't see much value on adding something like this.

Is there a use-case that would be made too complex by using a separate form for each step?

**Comment by pablo-abc** [comment]
@outerlook The way I'd see this is that JS only "augments" the experience. So most likely if you're planning on making your form work also without JS you would anyway need to add the attributes such as `required`, `min=...`, etc. This is why Felte adds the `novalidate` attribute on load, since you'll definitely not want browser validation if you already are using JS validation.

Using an action like you mentioned does raise a couple questions regarding implementation. Mainly if it would need to be implemented in the core package or if it's a niche enough use-case that can somehow be handled using an extender package (although this approach also raises some uncertainties).

Another thing is that most of the issues we are finding have more to do with when Felte sets a field to "touched" rather than when/how it validates it. Validation occurs always, but the error won't be present on the "errors" store until the field is "touched", which currently happens on blur and on change per field, or on all fields when the form is submitted.

**Comment by pablo-abc** [comment]
So regarding multi-page forms I've posted [a package to help with it](https://www.npmjs.com/package/@felte/multi-step), do not see this as a best practice yet since I am open for this to change a lot based on usage. There might be a lot of edge cases not considered. Seeing as the [implementation is not so big](https://github.com/pablo-abc/felte/blob/main/packages/multi-step/src/index.ts) this could eventually be merged to the core package. Although the current assumptions make it very simplistic.

Feel free to test it. I've created a [small example on CodeSandbox](https://codesandbox.io/s/felte-multi-step-demo-vyxh6?file=/App.svelte) to showcase an example of its usage. Do let me know of any edge cases you might find.

**Comment by ryanrussell** [comment]
@pablo-abc 

Awesome! I had built this with my own custom store and counter for a specific use case, but your implementation looks more robust and I see you've already stubbed out `decreaseStep()` as well. 

Official author support goes without saying as a better path...

Will port using your package, and post back if I find any edge cases or difficulties along the way.

Thanks so much for jumping on these bug and feature requests so quickly. You're a one man army!

**Comment by ryanrussell** [comment]
Just following up. 

Your multi step package seems to work well for me so far, I'd suggest closing this out...

If I come across some edge cases, I can put them in a new issue.

Thanks again for the support!

**Comment by pablo-abc** [comment]
@ryanrussell I'm leaving this open as I am still exploring per-field validation to handle this as well. But do open a new issue if you find anything in that package!

**Comment by outerlook** [comment]
I'm sorry I could not reach up earlier. I am reading it all but right now we are delivering a 650 files migration to svelte 😅

I imagine I will be able to test and contribute with some thoughts in 1,5 week...

**Comment by benbender** [comment]
@pablo-abc what you basically did here is to build a basic state-machine on top of `felte`. 
Tbh, Imho this is not the problem-domain which `felte` tries to solve. It's a nice example and/or helper but shouldn't go to core. Because as it expands the problem-domain unnecessarily and won't hold up more complex cases anyways. 

If your specific usecase isn't covered by the builtin store-concept by svelte (which is used in the helper), use something like @xstate/svelte (btw @xstate/fsm is very lightweight, powerful and a perfect match for this kind of problems).

So, imho there are two solutions to the multi-step/wizard-form-problem (and I have a clear preference):

- Either you show/hide some fields of the form depending on a step-count or similar. This would basically only ux-sugar and contradicts fundamental principles of html-forms and (most likely) usability/accessibility. This approach should be (at least) independent from submitting the form in a html/http-sense. If one opts for this approach, there is a ton of problems arising of you try to do it right for every edge-/use-case.

- Or, imho the better approach, you create individual forms per step. This could be perfectly handled by svelte as it is. In this case you have to carry over/combine the state of those individual forms with a simple store or a state-machine to submit it to an api or whatever in the last step. Felte's job in this solution is handling the form - and not the state-handling for the process at large. 

Btw: here is the `react-hook-foms`-example for such a case: https://react-hook-form.com/advanced-usage/#WizardFormFunnel and it uses the second approach as laid out above.

That said, there might be use-cases where field-level-validation is desirable (f.e. checking if a username is taken, pw-strength etc) and it would be a fair question if those are the responsibility of felte's validation-layer or if those should live in a customized input-component. I for myself lean towards the latter as it helps keeping bloat out of the nifty little core of felte :)
