### ISSUE TITLE
reporter-tippy error: 500  Cannot destructure property 'controls' of 'i' as it is undefined.

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#3]
When using Tippy to display validation errors, the page shows a 500 area when loading a page containing the form:  `500  Cannot destructure property 'controls' of 'i' as it is undefined.`.

If I pass `{single:true}` to the reporter method, this becomes `500   t is not a function`. 

```js
<script>
  import { createForm } from 'felte';
  import reporter from '@felte/reporter-tippy';
  import * as yup from 'yup';

  const schema = yup.object().shape({
    email: yup.string().email().required(),
    message: yup.string().required()
  });

  const { form } = createForm({
    extend: reporter(),
    onSubmit: (values) => {
      console.log(values);
    },
    validate: (values) => {
      try {
        schema.validate(values);
      } catch (err) {
        return err;
      }
    }
  });
</script>

<form use:form>
  <label for="email">Email:</label>
  <input id="email" name="email" aria-describedby="email-validation" />
  <div id="email-validation" aria-live="polite" />

  <label for="message">Message</label>
  <input type="text" name="message" aria-describedby="message-validation" />
  <div id="message-validation" aria-live="polite" />

  <button type="submit">submit</button>
</form>
```

**Comment by pablo-abc** [comment]
Part of this seems to be caused by the same issues I mentioned in #4

The other reason is that (as of now) [`@felte/reporter-tippy` does not accept any options](https://github.com/pablo-abc/felte/blob/main/packages/reporter-tippy/README.md). The `reporter` export is all that you need passed like:

```javascript
{
  // ...
  extend: reporter,
  // ...
}
```

**Comment by websocket98765** [comment]
With both changes, it works! Thanks.

Would it be possible to maintain the same signature for all reporters though--i.e. using either `extend: reporter()` or `extend: reporter({foo: true})`? It'd be a bit more consistent API, if it's possible.

**Comment by pablo-abc** [comment]
I'm still debating on what would be the best API to make reporters (or general packages that extend Felte's functionality) right now so I haven't focused that much on making it as consistent as it should be. The reason `@felte/reporter-dom` behaves differently is that while making it I realised passing some options to it would make it more useable.

It might make sense to do something similar for `@felte/reporter-tippy` to pass options to Tippy itself. But a consistent API is not my main worry right now during this moments. Specially since these packages are made more to choose one and forget the rest since you'll most likely only need one in your project..
