### ISSUE TITLE
@felte/reporter-dom: Validation errors not displayed, but are console logged.

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#4]
With the DOM reporter, I can submit the form data successfully. But I can't get it to show an error message if the validation failed--it shows no error in the DOM nodes for the validation error messages, but it logs to the browser console: `Uncaught (in promise) ValidationError: email must be a valid email` 

```js
<script>
  import { createForm } from 'felte';
  import reporterDom from '@felte/reporter-dom';
  import reporter from '@felte/reporter-tippy';
  import * as yup from 'yup';

  const schema = yup.object().shape({
    email: yup.string().email().required(),
    message: yup.string().required()
  });

  const { form } = createForm({
    extend: reporterDom(),
    onSubmit: (values) => {
      console.log('values', values);
    },
    validate: (values) => {
      try {
        schema.validate(values);
      } catch (err) {
        return err;
      }
    }
  });
</script>

<form use:form>
  <label for="email">Email</label>
  <input
    id="email"
    type="text"
    name="email"
    aria-describedby="email-validation"
  />
  <div
    id="email-validation"
    data-felte-reporter-dom-for="email"
    aria-live="polite"
  />

  <label for="message">Message</label>
  <input
    id="message"
    type="text"
    name="message"
    aria-describedby="message-validation"
  />
  <div
    id="message-validation"
    data-felte-reporter-dom-for="message"
    aria-live="polite"
  />

  <button type="submit">submit</button>
</form>
```

**Comment by pablo-abc** [comment]
Hi! Thanks for giving Felte a try. It seems I've made a huge mistake in the docs regarding Yup. I'll update that ASAP. (I added the part about yup in a rush).

First of all, `yup`'s `validate` function is asynchronous, so the reason it throws as an Uncaught Promise is because it's not being awaited in the `validate` function.

Second (and this is my mistake if you were doing this based on the docs), `yup` rejects with a `ValidationError` instance that doesn't match what Felte expects. A way to make it work (if your data object is not `deep` like here) is with a `validate` function like this one:

```javascript
    validate: async (values) => {
      try {
        await schema.validate(values, { abortEarly: false });
      } catch(err) {
        const errors = err.inner.reduce((res, value) => ({
          [value.path]: value.message,
          ...res,
        }), {});
        return errors;
      }
```

Adding a package to handle `yup`'s validation was in my roadmap, so this issue might as well push me into making one now. 😅.

It seems both of these might be what's causing the other issue you're experiencing in #3

Try this out and let me know if it keeps not working!

**Comment by pablo-abc** [comment]
Just so you know, I've [create a package to help with `yup` validation](https://www.npmjs.com/package/@felte/validator-yup) and update the [CodeSandbox demo](https://codesandbox.io/s/felte-demo-wce2h?file=/App.svelte) to show its usage.

**Comment by websocket98765** [comment]
This one works great! And is nice and clean. Thank you.

Given that `validator-up` imports `yup` already, what if it also exported it too to reduce lines of code needed by the user to just this?
```js
  import { validateSchema, yup } from '@felte/validator-yup';
```

**Comment by pablo-abc** [comment]
It's only using `yup` as a peerDependency. I didn't one to tie a specific version of `yup` to `validator-yup` (the same logic as I did with the `reporter-tippy` package) since someone might want to use their own version of use somewhere else unrelated to `Felte`.

**Comment by pablo-abc** [comment]
I'll close this since the issue described here is already solved. And that I feel not including `yup` bundled with `validator-yup` is the best approach now.

Thanks a lot for your input!
