### ISSUE TITLE
When initial data has object, felte generates wrong errors

### ISSUE THREAD

**Issue by eden-lane** [pablo-abc/felte#53]
I have schema where one field contains an object:
```js
const schema = yup.object({
    name: yup.string().required(),
    select: yup
      .object()
      .nullable()
      .default(null)
      .required("Required")
  });
```
When you pass initialValues to `createForm` function it generates an `error: null` for every field of the object:
```js
const { form, errors } = createForm({
  initialValues: {
    name: "Test",
    select: { value: "test", label: "Test" }
  }
});
```
errors in this case:
```js
{"name":null,"select":{"value":null,"label":null}}
```
but it should be 
```js
{"name": null, "select": null}
```

Here is the sandbox with this example:
https://codesandbox.io/s/felte-validation-problem-0dbbm?file=/App.svelte:154-222

**Comment by pablo-abc** [comment]
Hi! I can't quite catch here what the expected form layout is. Felte uses nested properties to refer to nested fields. Which means that your `initialValues` here would refer to three inputs/textareas/selects sort of like:

```html
<input name="name">
<input name="select.value">
<input name="select.label">
```

Is this what you're expecting to do?

**Comment by eden-lane** [comment]
Thank you for quick reply!
Actually no, I'm using svelte-select and it has an object as value. So in my case layout looks something like this:
```svelte
<Select items={items} on:select={handleSelect} bind:value={$data.select} />
```

In other words, I don't need errors for `select.value` and `svelte.label`, I just need one error for whole `select`. I've tried to reproduce it in yup alone, but it doesn't show any errors in this case because select has initial value and there is no error.
So I think the problem is in `validator-yup`

**Comment by pablo-abc** [comment]
Got it! So, as I said, Felte does always assume that nested properties are always nested fields. This is safe to assume since native HTML elements can't have an object as a value. So this has more to do with how `Felte` interprets your data.

In the case of `svelte-select` there are a few things happening:

1. It does not trigger any `input` or `change` events so Felte can't see it automatically. (Which is why I see you're using `bind` or `on:select`.
2. While `svelte-select` does seem to need an object as a value (in order to determine the `label` to show), Felte only needs the `value`.

In order for this to work, what I'd do is the following:

1. Completely remove the `bind:value` attribute (it is not necessary in this case).
2. Make your `handleSelect` function look something like this:

```javascript
function handleSelect(event) {
  $data.select = event.detail.value; // or `setField('select', event.detail.value)`
}
```

3. Change your validation object to require a `string` for the `select` field instead of an object.

```javascript
const schema = yup.object({
    name: yup.string().required(),
    select: yup.string().required(), // I assumed you wanted this to be required?
  });
```

```javascript
const { form, errors } = createForm({
  initialValues: {
    name: "Test",
    select: "test",
  }
});
```

In the end, the `label` property is only used for presentation purposes.

**Comment by pablo-abc** [comment]
Sorry for the delay! I've made you a small REPL example on how I would handle this [here](https://svelte.dev/repl/734a162ed7c445669c24a3a122782142?version=3.42.1). (I am using Zod here since Svelte's REPL does not like Yup for some reason, but the principle is the same).

**Comment by eden-lane** [comment]
Oh, now I see. Thank you so much for the help, it's priceless!
