### ISSUE TITLE
Objects in array is not working as expected

### ISSUE THREAD

**Issue by darkcris1** [pablo-abc/felte#56]
If I try to remove any field on nested objects, the data will validate the nested object even I did not touch it yet. 

If I also remove any field except the last field the last item will be remove even though I remove the second item. 

https://codesandbox.io/s/felte-demo-forked-umlmz?file=/App.svelte

**Comment by pablo-abc** [comment]
Sorry for the delay here.

So I've been playing around with this and I think I found why this is not working right now for you. A quick fix (in your case) would be to keep the state of the HTML input in sync with Felte by adding `value={$data.colors[index].value}` to the input itself.

The reason this is happening right now is that you're using the `data` store as a source of truth, and its index as the `key` for each input. Let's say we have 4 inputs as in your example, indexed as `0, 1, 2, 3`, if you try to remove the second one, the `data` store is updated correctly _BUT_ now the indexes of the array are `0, 1, 2`. So for _Svelte_ you've only removed the latest element, not the second, since you've keyed them using the `index`. And thus it doesn't update the `inputs` appropriately.

If you see the example I've made for Felte (which has a multi input like yours) [I'm using a more complex way to handle this in order to properly key it](https://codesandbox.io/s/felte-demo-wce2h?file=/App.svelte). But for your use-case (and most use-cases) just adding the `value` prop to force the DOM to be in sync with Felte should be ok.

**Comment by darkcris1** [comment]
I already did some workaround just like you stated, even if I force the value from the data source the error messages is not behaving as expected.

I don't think the key of the element is the problem here , I also did that multiple input example of yours but that approach will lead into a bunch of null values on array.

**Comment by pablo-abc** [comment]
It's been a long time but this _shouldn't_ be a problem anymore. Issues that were happening here have been solved during the following versions. Setting values to `null` was a previous intentional decision but this will change on v1.0.0 and behave as you would expect. [Here's your example using Felte v1](https://codesandbox.io/s/felte-demo-forked-bt0ks?file=/App.svelte).

Notes on it:

* `setField` no longer exists, we now use `setFields` with the same signature as before.
* We use `unsetField` which will update _all_ stores accordingly to maintain it in sync.
* `data-felte-unset-on-remove` no longer exists (this is the default behaviour now). There's a new `data-felte-keep-on-remove` that now would be needed in your case to prevent race conditions. (Since removing the field would also try to update the stores, but the stores are being updated by `unsetField`).

---

This issue will automatically be closed when I merge the v1 release.
