### ISSUE TITLE
on change events fire unintentionally

### ISSUE THREAD

**Issue by basaran** [pablo-abc/felte#67]
Hello again again :)

I have these initial values:

```
    multipleSelect: null,
    stateSelect: null,
    fruit: null,
```

and these are attached to three inputs. I think due to the way the change events are being monitored, this is what happens for instance, when I change the plain select fruit.

![events](https://user-images.githubusercontent.com/30809170/139203841-2a040001-1f3f-4f2a-9730-8a5a4e30a81e.gif)

Wouldn't the expected behavior be that only the fruit element gets marked? Like this one:

![input](https://user-images.githubusercontent.com/30809170/139203984-585d25c0-37d6-44a7-afd9-012e6c2c6681.gif)

and I did check, in none of these cases, the form is not submitting. But the $errors get updated like this in one shot:

![image](https://user-images.githubusercontent.com/30809170/139204169-775a4019-b61e-4acd-a613-cbc9e113ea85.png)

Code for fruit is as follows:

```
        <div>
            <label for="fruit" aria-invalid={$errors["fruit"]}>Fruit</label>
            <select id="fruit" name="fruit" bind:value={$data["fruit"]}>
                <option value="" selected>Select a fruit…</option>
                <option>…</option>
            </select>
        </div>
```

**Comment by pablo-abc** [comment]
Sorry for the (really late) reply. Had a pretty busy week. From what I've seen in this issue I'd say this is _intended_ behaviour. I wouldn't recommend using your stores inside your `transform` function. Specially since assigning to `data` can "touch" your fields (which is why it was displaying errors for fields you hadn't modified previously).
