### ISSUE TITLE
initial values and custom directives on inputs 

### ISSUE THREAD

**Issue by basaran** [pablo-abc/felte#68]
Hello,

I ran into another edge case while trying to use [imask](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/svelte-imask) directives on a standard DOM input.

```
Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.
```

Without the initialValues, it would mask the value nicely on page load. 

Would it be possible and make sense to have felte look for other directives on inputs/components and trigger them possibly when the initialValues are set?

If that's not the case, I suppose one can filter the initialValues object when handing it off to felte.

**Comment by pablo-abc** [comment]
Felte is largely vanilla JS with just light wrappers to make it work for a specific framework (which is what allowed it to also be used in Solid). So triggering actions or other directives is not that trivial to do. I'm guessing the reason why `imask` is not working here with `initialValues` is because programmatically changing an input's value does not trigger any event (this is how Felte sets `initialValues` when set on the config).

I don't have experience with `imask` but judging from that error message I'm guessing it should be possible to force it to run after initialisation of the form within an `onMount` call?

**Comment by basaran** [comment]
some components wouldn't expose re-update mechanisms, that's why I asked. I ended up filtering the `inititalValues` to exclude the `special` cases, and then bind separately. Thank you for the explanation.
