### ISSUE TITLE
Feature request: Additional stores for (initialValues, ) current values and html-controls

### ISSUE THREAD

**Issue by taffit** [pablo-abc/felte#83]
As I'm back using the wonderful Felte, please allow me to bother you again ;-) .    

Felte already has some stores for some data. What I (personally) would find helpful are stores for all the different states a form can have:
- Already discussed: initial values: There has already been a [discussion on this](https://github.com/pablo-abc/felte/issues/78). As it seems to be difficult to implement. These values can be used to check e. g. if some value has been changed or for resetting all the fields or showing in a tooltip the former value or ... Implementing this outside of Felte currently.
- *"current"* values: The values that you can see in the form. These can be different than the actual data, e. g. formatted values (you can use `transform` in Felte for this). Currently you need to do some `document.querySelector(input[name="myInput"])` to get the value displayed to the user.
- We already have the submitted values as `$data` in Felte: These are the cleaned, actual data that will be sent during submit.
- Another store containing the html-controls would be helpful as well. This way you could iterate through them and do some niceties like adding masks etc. Felte is probably already using something similar for validation, I guess.

Edit: some added information to make it clearer.    
Edit 2: I'm also happy with every hint you can give me to get to the data I need with some other method already available, that I may have overlooked. And I beg your pardon, I'm not a frontend-/JavaScript-crack.

**Comment by pablo-abc** [comment]
Sorry for the delay! Let me go over your points now:

* It's not so much that it's difficult to implement (we do this internally when we get initialValues from the fields themselves) but more about increasing Felte's API (and therefore having a more complex documentations for new users) for something that does not seem to provide as much extra value compared to handling it outside of Felte. From what I read on the other discussion the feature you want to implement is more akin to a "Unsaved changes" notification rather than a validation. I'm actually interested on this. Do you have any examples on if/how other frameworks handle this scenario? Since an indicator that the "form has changed" _is_ different than an indication that the "form has been touched" (the latter being what we support).
* This is something I've considered. Technically you _already_ have access to all of your elements through the [extender API](https://felte.dev/docs/svelte/extending-felte). The [should be available on mount](https://svelte.dev/repl/0250dc5b7a604bfeb044a04d44730524?version=3.44.2).

As of now, the `extend` property is the proposed way  to handle complex scenarios. But I'm open to debate here. (Specially exposing the controls argument, since you're not the first person that asks for this somewhere).

**Comment by taffit** [comment]
Hello @pablo-abc ,

thank you for your comment (and no reason at all to be sorry: I'm so happy that there is someone to react at all ;-)).    
I understand your concerns for extending the API, especially as the/some requested functionality is already available.

- You are right, my request was about identifying the unsaved changes. There is a use case for just checking if a field is touched and one to compare the fields to the initial values. My use case is to identify the single form fields out of a lot of fields (in a more sophisticated data centric app) must be sent to the backend (vs. sending all fields like in a contact form when something is touched). I Implemented it outside of felte currently and also the check if the whole form is dirty can then be implemented in one line.
- Thank you for the provided REPL. I will add this immediately to my code. I saw that you have access to the form controls for an extension, but it wasn't clear to me, what you would need to return in order to access them. Your code makes it clear to me now. Thank you!

Knowing how to access these, I don't need a store then. But maybe this could be a subject for the documentation as well. Thank you for your clarifications!

**Comment by pablo-abc** [comment]
An `$isDirty` store is something I can add, and seeing your use-case I feel it's a common enough scenario to be added to the API. This brings some considerations:

- `isDirty` would refer exclusively to user interactions with your form, so it is implied that there would be a relation between `touched` and `isDirty`, where if `$isDirty === true` then the form _has_ to be touched. But a `touched` form is not necessarily dirty (since you can just focus and blur a field without making it touched).
- I'm not sure what the better UX is here. In most forms I've seen that handle `unsaved changes` I've seen this behaviour: you change the value of the field, then the form would be dirty; if you then manually type back the original value of the field the form would still say there are `unsaved changes` even though the `initial values` and `current values` are the same. So the implementation usually looks more like `on:input={() => $isDirty = true}`. This would be way lighter than comparing your current values to `initialValues` every time `data` changes. Does Formula also behave like this? Or do they compare its initial values to the current values after each change?

The answer to the last point would determine if exposing a way to change `initialValues` programmatically is necessary or not.

**Comment by taffit** [comment]
👍    
In my case I revert to untouched/not dirty, if the value is changed back to the initial value, but this is just my special case. Your described behavior will match most use cases, I guess, so fine for me.

**Comment by pablo-abc** [comment]
This got closed automatically after merging #85. It is already published and feel free to reopen this or create a new issue of something here is not working correctly.
