### ISSUE TITLE
Form components for Svelte?

### ISSUE THREAD

**Issue by AgarwalPragy** [pablo-abc/felte#92]
The doc mentions that  Felte doesn't export any components as of now.

> Felte does not export any components like Form, Field or anything like that, but you do need to make felte aware of your inputs by assigning a name to them.

Coming from React's Formik, I feel that Felte should provide some components and contexts to ease the creation of custom form elements.

Functions like `getField` and `setField` are only available when you call `createForm`. If you're trying to create a custom form element that needs the value of a field based on the name, you have to manually create a context and pass it down. Since this is a repetitive task, it would be nice to have an inbuilt solution for this.

**Comment by pablo-abc** [comment]
Hey, @AgarwalPragy! Are you using Svelte with Felte? The main reason I opted against exporting components is that styling third party is not as easy in Svelte as it is in React. So the whole objective of using the `createForm` function is that, in most simple cases you only need to do `<form use:form>` and the test of the form can be written as a normal HTML form. The `name` attribute is completely normal, and expected if you're not using JS to handle your forms.

---

Regarding using context, I've left that out since I can't think of a reason why you'd have your custom inputs deep within the component tree. There's two scenarios that I see can happen with custom components:

- It uses a native HTML input within it, which means that as long as you can assign the `name` attribute to that input `Felte` will track it.
- It does not use an HTML input, but it generally sends an event (e.g. `on:change`) or exposes a prop (e.g. `onChange`), on both cases you would use the `setField` helper there on the same component as your `createForm` so you could have a form like this:

```html
<form use:form>
  <!-- If your custom component uses a native HTML input -->
  <CustomInputWithName name="namedInput" />
  <!-- If your custom component does not use a native HTML input -->
  <CustomComponentWithEvent on:change={(e) => setFIeld('unnamedInput', e.detail.value)} />
</form>
```

If you _do_ have custom inputs within your component tree then I guess you're doing something a bit more complex and it does make sense to me that this would also require a bit more complex solution (e.g. creating your own `context`).

Is there any basic scenario that would not be covered by the above approaches?

**Comment by pablo-abc** [comment]
I'm closing this since this is not something that I feel Felte should do. And using custom form elements can generally be done with the returned helpers.
